name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: pip install poetry
    - uses: actions/checkout@v3
    - run: make install-dependencies
    - run: make test
